openapi: 3.0.1
info:
  title: qarax API
  version: 0.1.0
  description: The API for qarax manager
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
externalDocs:
  description: Find out more about Qarax
  url: "https://github.com/qarax/qarax"
tags:
  - name: Hosts
  - name: Vms
components:
  schemas:
    StringResponse:
      properties:
        response:
          type: string
    Host:
      properties:
        address:
          type: string
        host_user:
          type: string
        id:
          format: uuid
          type: string
          readOnly: true
        name:
          type: string
        password:
          type: string
          writeOnly: true
        port:
          format: int32
          type: integer
        status:
          type: string
          readOnly: true
          enum:
            - up
            - down
            - unknown
            - initializing
            - installing
            - installation_failed

    Vm:
      properties:
        id:
          format: uuid
          type: string
          readOnly: true
        name:
          type: string
        status:
          type: string
          readOnly: true
          enum:
            - up
            - down
            - unknown
        host_id:
          format: uuid
          type: string
        vcpu:
          format: int32
          type: integer
        memory:
          format: int32
          type: integer
        ip_address:
          format: ipv4
          type: string
        mac_address:
          type: string
        network_mode:
          type: string
          enum:
            - dhcp
            - static_ip
        kernel_parameters:
          type: string
        kernel:
          type: string
    Error:
      type: object
      properties:
        error:
          type: string
    CreationResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
paths:
  /hosts:
    get:
      operationId: listHosts
      summary: Get hosts list
      description: Get hosts list
      tags:
        - Hosts
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Host"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      operationId: addHost
      summary: Create new host
      description: Create new host
      tags:
        - Hosts
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Host"
        required: true
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreationResponse"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  "/hosts/{hostId}":
    get:
      operationId: getHost
      summary: Get host by ID
      description: ''
      tags:
        - Hosts
      parameters:
        - name: hostId
          in: path
          description: ID of host
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Host"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  "/hosts/{hostId}/install":
    post:
      operationId: installHost
      summary: Install qarax node on host
      description: Install and run qarax-node on host
      tags:
        - Hosts
      parameters:
        - name: hostId
          in: path
          description: ID of host
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StringResponse"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  "/hosts/{hostId}/healthcheck":
    post:
      operationId: healthcheck
      summary: Healthcehck a host
      description: Runs healthcheck on a host, currently just ensures gRPC connectivity
      tags:
        - Hosts
      parameters:
        - name: hostId
          in: path
          description: ID of host
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StringResponse"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /vms:
    get:
      operationId: listVms
      summary: Get VM list
      description: Get VM list
      tags:
        - VMs
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Vm"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      operationId: addVm
      summary: Create new VM
      description: Create new VM
      tags:
        - VMs
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Vm"
        required: true
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreationResponse"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  "/vms/{vmId}":
    get:
      operationId: getVm
      summary: Get VM by ID
      description: ""
      tags:
        - VMs
      parameters:
        - name: vmId
          in: path
          description: ID of VN
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Vm"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  "/vms/{vmId}/start":
    post:
      operationId: startVm
      summary: Start a VM
      description: Start a VM on an available host
      tags:
        - VMs
      parameters:
        - name: vmId
          in: path
          description: ID of VM
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StringResponse"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  "/vms/{vmId}/stop":
    post:
      operationId: stopVm
      summary: Stop a VM
      description: ""
      tags:
        - VMs
      parameters:
        - name: vmId
          in: path
          description: ID of VM
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StringResponse"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
