application:
  port: 8000
database:
  host: "localhost"
  port: 5432
  username: "qarax"
  password: "qarax"
  database_name: "qarax"
  max_connections: 10
vm_defaults:
  kernel: "/var/lib/qarax/images/vmlinux"
  initramfs: "/var/lib/qarax/images/test-initramfs.gz"
  cmdline: "console=ttyS0 reboot=k panic=1 pci=off"
